version: "3.9"

services:
  qr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-api
    command: python run_qr.py
    ports:
      - "6002:6002"
    restart: unless-stopped
    volumes:
      - ./output:/app/output