version: "3.9"

services:
  qr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-api
    ports:
      - "6003:6003"
    restart: unless-stopped
    volumes:
      - ./output:/app/output
