version: "3.9"

services:
  qr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-api
    command: python run_qr.py
    ports:
      - "6001:6001"
    restart: unless-stopped
    volumes:
      - ./output:/app/output

  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    command: python run_chatbot.py
    ports:
      - "6002:6002"
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=your_gemini_api_key_here
